<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="gov.nasa.jpf.test.mc.threads.DaemonTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2018-10-23T18:35:31" hostname="boombox" time="0.264">
  <properties/>
  <testcase name="testRace" classname="gov.nasa.jpf.test.mc.threads.DaemonTest" time="0.264"/>
  <system-out><![CDATA[  running jpf with args:
JavaPathfinder core system v8.0 (rev 28c066f86c2cd268b8c9b9959161e3d07c6146c6) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.mc.threads.DaemonTest.runTestMethod()

====================================================== search started: 23/10/18 19:35

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.RuntimeException: blow up
	at gov.nasa.jpf.test.mc.threads.DaemonTest$T1.run(DaemonTest.java:42)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:

thread gov.nasa.jpf.test.mc.threads.DaemonTest$T1:{id:1,name:Thread-1,status:RUNNING,priority:5,isDaemon:true,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.test.mc.threads.DaemonTest$T1.run(DaemonTest.java:42)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.RuntimeException: blow up  at gov.nasa.j..."

====================================================== search finished: 23/10/18 19:35
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
