<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="gov.nasa.jpf.test.vm.basic.InitializeInterfaceClassObjectRefTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2018-10-23T18:36:10" hostname="boombox" time="0.268">
  <properties/>
  <testcase name="test" classname="gov.nasa.jpf.test.vm.basic.InitializeInterfaceClassObjectRefTest" time="0.268"/>
  <system-out><![CDATA[  running jpf with args: +log.finest+=,gov.nasa.jpf.vm.ClassInfo
JavaPathfinder core system v8.0 (rev 28c066f86c2cd268b8c9b9959161e3d07c6146c6) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.InitializeInterfaceClassObjectRefTest.runTestMethod()

====================================================== search started: 23/10/18 19:36

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.RuntimeException: This test throws an expected exception.
	at gov.nasa.jpf.test.vm.basic.InitializeInterfaceClassObjectRefTest.test(InitializeInterfaceClassObjectRefTest.java:41)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:650)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.RuntimeException: This test throws an ex..."

====================================================== search finished: 23/10/18 19:36
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
